In [2]:
import pandas as pd

In [4]:
data = [2,5,7]
pd.DataFrame(l)

   0
0  2
1  5
2  7

In [6]:
age = [28,32,35,24]
df = pd.DataFrame(age,index= ["A","B","C","D"],columns=["age"])

In [7]:
df

   age
A   28
B   32
C   35
D   24